//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superheroes.Repository.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.ISuperheroService")]
    public interface ISuperheroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/GetAll", ReplyAction="http://tempuri.org/ISuperheroService/GetAllResponse")]
        System.Collections.Generic.List<Superheroes.DataModel.Superhero> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/GetAll", ReplyAction="http://tempuri.org/ISuperheroService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Superheroes.DataModel.Superhero>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Get", ReplyAction="http://tempuri.org/ISuperheroService/GetResponse")]
        Superheroes.DataModel.Superhero Get(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Get", ReplyAction="http://tempuri.org/ISuperheroService/GetResponse")]
        System.Threading.Tasks.Task<Superheroes.DataModel.Superhero> GetAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Add", ReplyAction="http://tempuri.org/ISuperheroService/AddResponse")]
        void Add(Superheroes.DataModel.Superhero superhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Add", ReplyAction="http://tempuri.org/ISuperheroService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(Superheroes.DataModel.Superhero superhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Update", ReplyAction="http://tempuri.org/ISuperheroService/UpdateResponse")]
        void Update(string name, Superheroes.DataModel.Superhero superhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Update", ReplyAction="http://tempuri.org/ISuperheroService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string name, Superheroes.DataModel.Superhero superhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Delete", ReplyAction="http://tempuri.org/ISuperheroService/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/Delete", ReplyAction="http://tempuri.org/ISuperheroService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/UpdateAll", ReplyAction="http://tempuri.org/ISuperheroService/UpdateAllResponse")]
        void UpdateAll(System.Collections.Generic.List<Superheroes.DataModel.Superhero> superhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperheroService/UpdateAll", ReplyAction="http://tempuri.org/ISuperheroService/UpdateAllResponse")]
        System.Threading.Tasks.Task UpdateAllAsync(System.Collections.Generic.List<Superheroes.DataModel.Superhero> superhero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuperheroServiceChannel : Superheroes.Repository.WCF.ISuperheroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuperheroServiceClient : System.ServiceModel.ClientBase<Superheroes.Repository.WCF.ISuperheroService>, Superheroes.Repository.WCF.ISuperheroService {
        
        public SuperheroServiceClient() {
        }
        
        public SuperheroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperheroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperheroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperheroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Superheroes.DataModel.Superhero> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Superheroes.DataModel.Superhero>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Superheroes.DataModel.Superhero Get(string name) {
            return base.Channel.Get(name);
        }
        
        public System.Threading.Tasks.Task<Superheroes.DataModel.Superhero> GetAsync(string name) {
            return base.Channel.GetAsync(name);
        }
        
        public void Add(Superheroes.DataModel.Superhero superhero) {
            base.Channel.Add(superhero);
        }
        
        public System.Threading.Tasks.Task AddAsync(Superheroes.DataModel.Superhero superhero) {
            return base.Channel.AddAsync(superhero);
        }
        
        public void Update(string name, Superheroes.DataModel.Superhero superhero) {
            base.Channel.Update(name, superhero);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string name, Superheroes.DataModel.Superhero superhero) {
            return base.Channel.UpdateAsync(name, superhero);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public void UpdateAll(System.Collections.Generic.List<Superheroes.DataModel.Superhero> superhero) {
            base.Channel.UpdateAll(superhero);
        }
        
        public System.Threading.Tasks.Task UpdateAllAsync(System.Collections.Generic.List<Superheroes.DataModel.Superhero> superhero) {
            return base.Channel.UpdateAllAsync(superhero);
        }
    }
}
